chore: ajuste de regra no pre-commit

diff --git a/.husky/pre-commit b/.husky/pre-commit
--- a/.husky/pre-commit
+++ b/.husky/pre-commit
@@ -1,4 +1,23 @@
 #!/usr/bin/env sh
 . "$(dirname -- "$0")/_/husky.sh"
 
-npm run pre-commit && npm run lint
+#!/usr/bin/env bash
+if git diff --cached --name-only | xargs grep -n 'fdescribe('
+  then
+  echo "Error: 'fdescribe' encontrado. Por favor remova antes de realizar o commit."
+  exit 1
+fi
+
+if git diff --cached --name-only | xargs grep -n 'fit('
+  then
+  echo "Error: 'fit' encontrado. Por favor remova antes de realizar o commit."
+  exit 1
+fi
+
+if git diff --cached --name-only | xargs grep -n 'console.'
+  then
+  echo "Error: 'console' encontrado. Por favor remova antes de realizar o commit."
+  exit 1
+fi
+
+npm run pre-commit
